---
title: "lab09-Kayla-Fathi.Rmd"
author: "Kayla Fathi"
date: "10/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Part 2) Basics of Strings Manipulation

```{r}
head(USArrests)
states <- rownames(USArrests)
head(states)

tolower(states)
toupper(states)
casefold(states)
```

#### Number of characters 

```{r}
nchar(states)
```

#### Case folding

```{r}
tolower(states)
toupper(states)
casefold(states)
```

#### Length of state names

```{r}
num_chars <- nchar(states)
char_freqs <- table(num_chars)
barplot(char_freqs)
```

#### Pasting strings

```{r}
paste('Pumpkin', 'Pie')
paste(states[1:5], num_chars[1:5], sep = " = ")
paste(states[1:5], collapse ='')

```

#### Permutations

```{r}
factorial(7)
```

#### Substrings

```{r}
states1 <- substr(states, 1,3)
statesend <- substr(states, nchar(states)-2, nchar(states))
statesmix <- paste0(substr(states1,1,1), statesend)
statesmix
```

#### Converting from Fahrenheit Degrees

```{r}
to_celsius <- function(x = 1) {
  (x - 32) * (5/9)
}

to_kelvin <- function(x = 1) {
  (x + 459.67) * (5/9)
}

to_reaumur <- function(x = 1) {
  (x - 32) * (4/9)
}

to_rankine <- function(x = 1) {
  x + 459.67
}

temp_convert <- function(x = 1, to = "celsius") {
  switch(to,
         "celsius" = to_celsius(x),
         "kelvin" = to_kelvin(x),
         "reaumur" = to_reaumur(x),
         "rankine" = to_rankine(x))
}

temp_convert(30, 'celsius')

temp_convert <- function(x = 1, to = "celsius") {
  to = casefold(to)
  switch(to,
         "celsius" = to_celsius(x),
        "kelvin" = to_kelvin(x),
         "reaumur" = to_reaumur(x),
         "rankine" = to_rankine(x))
}

temp_convert(30, 'celsius')
temp_convert(30, 'Celsius')
temp_convert(30, 'CELSIUS')
```

### Names of Files

```{r}
file1 <- paste0('file', 1:10, '.csv')
file1
paste('file', 1:10, '.csv', sep = '')
file3 <- rep(0,10)
for (i in 1:10) { file3[i] <- paste0('file', i,'.csv')
}
file3
```


```{r}
substr(file3, 5, nchar(file3))
paste0("dataset",substr(file3, 5, nchar(file3)))

```

#### Using function cat()

```{r}
# name of output file
outfile <- "output.txt"
cat("---", file = outfile)
cat("\n","title: Lab09", file = outfile, append = TRUE )
cat("\n", "author: Kayla Fathi", file = outfile, append = TRUE)
cat("\n", "date: 10/25/18", file = outfile, append = TRUE)
cat("\n", "output: html_document", file = outfile, append = TRUE)
cat("\n", "---", file = outfile, append = TRUE)
cat("\n", file = outfile, append = TRUE)
# writing to 'outfile.txt'
cat("\n","This is the first line", file = outfile, append = TRUE)
# insert new line
cat("\n", file = outfile, append = TRUE)
cat("A 2nd line", file = "output.txt", append = TRUE)
# insert 2 new lines
cat("\n\n", file = outfile, append = TRUE)
cat("\nThe quick brown fox jumps over the lazy dog\n",
    file = outfile, append = TRUE)

```

#### Valid color names

```{r}
is_color <- function(x) {
  colors(x) 
  
colors <- colors()
"white" %in% colors
}
```

